### ISSUE TITLE
overriding a provider template

### ISSUE THREAD

**Issue by oweng** [sous-chefs/redisio#124]
Hi,

first off sorry, I have tried the chef community, but have not found an answer.  We have our own init.d script we use for redis.  I have tried chef-rewind, but it didn't seem to work.  Is there a way that I am just missing, that I could use to override the init.d template in redisio/providers/install.rb?

Thank you,

Geoff

**Comment by Xorima** [comment]
Closing as old issue, please open a new issue if this is still a problem?
