### ISSUE TITLE
sentinel down-after-milliseconds &  failover-timeout underscore vs hyphen 

### ISSUE THREAD

**Issue by yonatan-ess** [sous-chefs/redisio#370]
in redis_sentinel.rb : 
  'down-after-milliseconds' => 30000,
  'failover-timeout'        => 900000,

while in sentinel.conf.erb: 
#{current['failover_timeout']}"
 #{current['down_after_milliseconds']}"

**Comment by devsibwarra** [comment]
@yonatan-ess This appears to be setup correctly in `master` (redisio version `2.7.1`).

https://github.com/brianbianco/redisio/blob/master/attributes/redis_sentinel.rb#L34
```
  'failover-timeout'        => 900000,
```

https://github.com/brianbianco/redisio/blob/master/providers/sentinel.rb#L126
```
masters = [{ ...
            failover_timeout:             current['failover-timeout'] || current[:failovertimeout]
... }]
```

https://github.com/brianbianco/redisio/blob/master/templates/default/sentinel.conf.erb#L116-L119
```
<% @masters.each do |current| %>
<% calc_name = String(current['master_name'] || @name || 'master_name') %>
<%= "sentinel failover-timeout #{calc_name} #{current['failover_timeout']}" unless current['failover_timeout'].nil? %>
<% end %>
```

What problem are you trying to fix?
