### ISSUE TITLE
Sous-chefs adoption 

### ISSUE THREAD

**Issue by damacus** [sous-chefs/redisio#373]
Hey there,

The friendly folks over at sous-chefs would like to adopt this cookbook. Would you be up for transferring?

**Comment by brianbianco** [comment]
Seems like a good idea to me 👍🏻

**Comment by damacus** [comment]
Ace! 

Here's a quick guide on transferring. I'd love if you could stick around and occasionally help out with this cookbook, even though you work on Chef much less these days! 👍 

http://sous-chefs.org/transferring/

**Comment by josephholsten** [comment]
@brianbianco if you aren't going to be able to transfer the cookbook, we can fork if you prefer. We have a process, but it's nowhere near as pleasant for end users if we end up doing this:

https://sous-chefs.org/forking/

If you do want to transfer, the only parts of the [transferring guide](http://sous-chefs.org/transferring/) you need to do are [Transferring the code > From a single-cookbook repo in GitHub](https://sous-chefs.org/transferring#from-a-single-cookbook-repo-in-github) and [Transferring the cookbook in Supermarket](https://sous-chefs.org/transferring#transferring-the-cookbook-in-supermarket). We can handle all the work from there!

**Comment by brianbianco** [comment]
Sorry, I intend to get to this, I'm just busy with life :)

**Comment by majormoses** [comment]
@brianbianco I am a member of `sous-chefs` if you make me an admin on this repo (right now I have push access) I can help facilitate the transfer.

**Comment by tas50** [comment]
@brianbianco if you'd like to move things over feel free to transfer the repo to myself or to @majormoses or @damacus and we can transfer it into sous-chefs. We'd really appreciate the change to continue your work with the folks in the community that are using this cookbook.

-Tim (Chef)

**Comment by brianbianco** [comment]
@tas50 It says I cannot transfer to your because the repository already exists for you :)

**Comment by tas50** [comment]
@brianbianco I nuked my fork. Try it again

**Comment by brianbianco** [comment]
@tas50 congrats on your new repo.  Let me know if you need anything on the chef supermarket side of things.

**Comment by tas50** [comment]
I handled the supermarket bit since I'm admin there. Thanks for the transfer. 👍

**Comment by brianbianco** [comment]
@tas50 take good care of her, I like to think she's been a good cookbook for somebody somewhere.

**Comment by josephholsten** [comment]
@brianbianco she's been an essential tool at one of my previous jobs, and has made countless users happy. Thanks for all the excellent work!

**Comment by brianbianco** [comment]
@josephholsten Ah well then it was worth it.  My only regret is that I didn't have more free time and didn't burn out on it.  Thanks it means a lot to hear the years of work I dumped into it helped somebody.

**Comment by tas50** [comment]
@brianbianco I used this at 3 different jobs. You helped support a pile of web analytics, A/B web testing, and streaming videos.

**Comment by majormoses** [comment]
@brianbianco Ya I also have used this cookbook pretty heavily in at least 3 companies and still use it lightly. Everything from online gaming, web applications, analytics, and monitoring. I am sure I am missing a few more use cases.
