### ISSUE TITLE
Fatal error with selinux_policy >= 2.2.0

### ISSUE THREAD

**Issue by PowerKiKi** [sous-chefs/redisio#377]
I get the following error when using this cookbook and latest selinux_policy 2.2.0.

selinux_policy 2.2.0 was released a [few hours ago](https://github.com/sous-chefs/selinux_policy/releases/tag/v2.2.0) and contains a [breaking change in the `use_selinux` method](https://github.com/sous-chefs/selinux_policy/commit/bf9f5a33e67e22952e42ca2a1b3eed22bd7bd95d#diff-38a4aeddb4e620724d3b85362cb8b939R8) which was added 7 months ago but is only released now.

I am not sure whether this method should still be used, but I'll try to submit a PR.

@chewi, as the person who [added selinux support to this cookbook](https://github.com/brianbianco/redisio/commit/f44c5241b20d4fe164cf814de8a61c8ee95ce5c8), would you have any comment on the situation ?

```
================================================================================
Error executing action `run` on resource 'redisio_configure[redis-servers]'
================================================================================

ArgumentError
-------------
wrong number of arguments (given 0, expected 1)

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/selinux_policy/libraries/helpers.rb:8:in `use_selinux'
/tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:99:in `block (2 levels) in configure'
/tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:98:in `block in configure'
/tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:42:in `each'
/tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:42:in `configure'
/tmp/kitchen/cache/cookbooks/redisio/providers/configure.rb:24:in `block in class_from_file'

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/redisio/recipes/configure.rb

34: redisio_configure 'redis-servers' do
35:   version redis['version'] if redis['version']
36:   default_settings redis['default_settings']
37:   servers redis_instances
38:   base_piddir redis['base_piddir']
39: end
40: 
```

**Comment by PowerKiKi** [comment]
This is also related to https://github.com/sous-chefs/selinux_policy/issues/90 and maybe we should for that issue to solved first before doing something here...

**Comment by chewi** [comment]
Unfortunately I recently left the company where I was using Chef. I know this use_selinux method is used in several cookbooks and, at a glance, I think they could have made it backwards compatible by defaulting to the old node attribute value.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shoekstra** [comment]
Hi @PowerKiKi, @chewi,

The best option would be to use the native `selinux_enabled?` helper in Chef core and not use the helper from the selinux_policy cookbook.

I created #379 to discuss if this cookbook should even manage SELinux, to me it's out of scope of what a redis cookbook should manage - appreciate any thoughts/comments!

Stephen

**Comment by brianbianco** [comment]
It is true this cookbook manages many things it should not manage (including like you point out se linux).  Unfortunately we don't know how many people rely on that behavior.

The best option is to probably just have a flag that lets you opt out of se linux config (and any other out of scope configs its trying to do for convenience)
