### ISSUE TITLE
can't do notifies on config file change

### ISSUE THREAD

**Issue by bakins** [sous-chefs/redisio#44]
Because the template for the redis config is wrapped in recipe_eval there's no way to subscribe to it to restart the redis service(s) on changes.

**Comment by TinaTina** [comment]
but log file is touched all the time, there's no point in subscribing when it gets triggered all the time. 
why using touch instead of create? https://github.com/brianbianco/redisio/blob/master/providers/configure.rb#L147-L157

**Comment by martinb3** [comment]
@TinaTina You're commenting on an issue closed over 2 years ago. This cookbook was almost completely re-written in between now and then. Are you sure you're even talking about the same thing?

**Comment by TinaTina** [comment]
@martinb3 sorry, I'm not talking about the issue here. The problem I'm encountering is largely due to the redisio_configure lwrp not being idempotent.

**Comment by brianbianco** [comment]
Well if the current versions configure lwrp is not idempotent that is a serious issue. Do you know where in the code the culprit is @TinaTina

**Comment by TinaTina** [comment]
@brianbianco I opened issue #215 and provided detailed description of what the cause is.
