### ISSUE TITLE
WARNING: Sentinel was not able to save the new configuration on disk!!!: Permission denied

### ISSUE THREAD

**Issue by zedtux** [sous-chefs/redisio#450]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

With the latest Redis version at least (6.2.6), when running this cookbook, I have 2 warning messages:

```
Could not create tmp config file (Permission denied)
WARNING: Sentinel was not able to save the new configuration on disk!!!: Permission denied
```

## :pancakes: Cookbook version

6.1.0
## :woman_cook:  Chef-Infra Version

17.9.26

## :tophat: Platform details

Ubuntu 20.04

## :police_car: Expected behavior

The cookbook should set permissions of the `/etc/redis` directory so that the `redis` user is allowed to write on files.

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by zedtux** [comment]
To me the issue is in the [block of code creating the configuration directory](https://github.com/sous-chefs/redisio/blob/main/providers/configure.rb#L92-L98) which doesn't sets the `group` to `redis` (at least for Ubuntu, probably Debian too), and it sets the permissions to `755` which doesn't allow `redis` user to write: it should be `775`.

**Comment by ramereth** [comment]
@zedtux please feel free to create a PR which fixes this.
