### ISSUE TITLE
Initd script - why check pidfile exists?

### ISSUE THREAD

**Issue by allaire** [sous-chefs/redisio#70]
Hi,

Why is it pertinent to have this if statement?:
https://github.com/brianbianco/redisio/blob/master/templates/default/redis.init.erb#L45

I use monit to monitor redis, and I can't restart it, since it keeps saying that a pid file already exists. I removed the if so `eval $EXEC` is always called no matter if there's a pidfile or not, and it worked wonderfully.

Also, is there any way to have a pid file when using upstart script? I like to use upstart and defer to Monit the cpu/memory alerting + restarting the app via upstart, but it looks like it don't create any pid file:
https://github.com/brianbianco/redisio/blob/master/templates/default/redis.conf.erb#L17

Thanks for the h elp

**Comment by Xorima** [comment]
Closing as old issue, please reopen if this is still a problem?
